# Streamlit Cloud Secrets Configuration
# Add these secrets in Streamlit Cloud dashboard

[aws]
AWS_ACCESS_KEY_ID = "your-aws-access-key-here"
AWS_SECRET_ACCESS_KEY = "your-aws-secret-key-here"
AWS_DEFAULT_REGION = "us-west-2"

[s3]
S3_BUCKET_NAME = "uci-research-data-bucket"
S3_REGION = "us-west-2"

[app]
APP_ENV = "production"
DEBUG = false
LOG_LEVEL = "INFO"

[model]
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "claude-3-haiku-20240307-v1:0"
MAX_TOKENS = 1000
TEMPERATURE = 0.3

[cost]
MAX_MONTHLY_SPEND = 100.00
ALERT_THRESHOLD = 50.00

[features]
ENABLE_CACHE = true
ENABLE_MONITORING = true
ENABLE_ANALYTICS = false